apiVersion: v1
kind: Service
metadata:
    name: "sal-dc5e"
    labels:
        app: "sal-dc5e"
spec:
    type: LoadBalancer
    ports:
    - port: 88
      targetPort: 88
      protocol: TCP
      name: http
    selector:
        app: "sal-dc5e"